---
name: 'Ansible Android role workflow'

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  tests:
    name: 'Run tests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v4'
      - name: 'ansible-lint'
        uses: 'ansible/ansible-lint@main'
  release:
    name: 'Publish to Ansible Galaxy'
    if: startsWith(github.ref, 'refs/tags/v') && github.base_ref == 'master'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v4'
      - name: 'galaxy'
        uses: 'robertdebock/galaxy-action@1.2.0'
        with:
          galaxy_api_key: '${{ secrets.galaxy_api_key }}'
          git_branch: 'master'
